name: Floristics
main: land.jay.floristics.Floristics
version: 2.5.1
api-version: 1.15
softdepend: [GriefPrevention, WorldGuard, RedProtect, Towny, Vivaldi]
commands:
    floristics:
        aliases: flo
        description: enable or disable growth in GriefPrevention claims or Towny towns
        usage: /floristics ...
